---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.6.1
_src_path: gh:radio-aktywne/template-meta
accountname: radio-aktywne
description: NestJS app template 🐈
reponame: template-app-nest
repourl: https://github.com/radio-aktywne/template-app-nest
templatename: nest
type: app
